# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f0fce40f6c42d1c15dc2e9fb12b6d938c3c0ca5037da3666f5e7dd3abcf6a0863b24b2e0ec5785fde67ec5e1cbd0ff1f02bbf2afa0354d4bc36d62e6f8fe497

test:
  secret_key_base: cc6fcd34f3e380caa50edeb7106ee17758b591192c0dcde45e18ed70d5dca71674c321ea5291711c78aa028317e4419f2075163f1fd760b1524cc467868454a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
